/* istanbul ignore file */
import { newDb } from "pg-mem";
import { describe, expect, it } from "vitest";

import UserDeviceService from "../model/userDevice/service";
import createConfig from "./helpers/createConfig";
import createDatabase from "./helpers/createDatabase";

const CREATE_TABLE_SQL = `
  CREATE TABLE user_devices (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    device_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
`;

describe("UserDeviceService — getByUserId", async () => {
  const db = newDb();
  db.public.none(CREATE_TABLE_SQL);
  db.public.none(`
    INSERT INTO user_devices (user_id, device_token) VALUES
      ('user-1', 'token-a'),
      ('user-1', 'token-b'),
      ('user-2', 'token-c');
  `);

  const config = createConfig();
  const database = await createDatabase({ db });
  const service = new UserDeviceService(config, database);

  it("returns all devices for a given userId", async () => {
    const result = await service.getByUserId("user-1");

    expect(result).toHaveLength(2);
    expect(result?.every((d) => d.userId === "user-1")).toBe(true);
  });

  it("returns device tokens for the user", async () => {
    const result = await service.getByUserId("user-1");
    const tokens = result?.map((d) => d.deviceToken).toSorted();

    expect(tokens).toEqual(["token-a", "token-b"]);
  });

  it("returns an empty array when user has no devices", async () => {
    const result = await service.getByUserId("user-unknown");

    expect(result).toEqual([]);
  });

  it("does not return devices belonging to other users", async () => {
    const result = await service.getByUserId("user-2");

    expect(result).toHaveLength(1);
    expect(result?.[0].deviceToken).toBe("token-c");
  });
});

describe("UserDeviceService — removeByDeviceToken", async () => {
  const db = newDb();
  db.public.none(CREATE_TABLE_SQL);
  db.public.none(`
    INSERT INTO user_devices (user_id, device_token) VALUES
      ('user-1', 'token-to-delete'),
      ('user-1', 'token-keep');
  `);

  const config = createConfig();
  const database = await createDatabase({ db });
  const service = new UserDeviceService(config, database);

  it("returns the deleted device record", async () => {
    const result = await service.removeByDeviceToken("token-to-delete");

    expect(result).toBeDefined();
    expect(result?.deviceToken).toBe("token-to-delete");
    expect(result?.userId).toBe("user-1");
  });

  it("removes the device from the database", async () => {
    const remaining = await service.getByUserId("user-1");

    // token-to-delete was removed in the previous test, only token-keep remains
    expect(remaining).toHaveLength(1);
    expect(remaining?.[0].deviceToken).toBe("token-keep");
  });

  it("returns null when the token does not exist", async () => {
    const result = await service.removeByDeviceToken("nonexistent-token");

    // slonik's maybeOne returns null (not undefined) when no row is found
    expect(result).toBeNull();
  });
});

describe("UserDeviceService — preCreate (deduplication)", async () => {
  const db = newDb();
  db.public.none(CREATE_TABLE_SQL);
  db.public.none(`
    INSERT INTO user_devices (user_id, device_token) VALUES ('user-1', 'existing-token');
  `);

  const config = createConfig();
  const database = await createDatabase({ db });
  const service = new UserDeviceService(config, database);

  it("removes the existing row with the same deviceToken before creating", async () => {
    await service.create({ deviceToken: "existing-token", userId: "user-2" });

    const user1Devices = await service.getByUserId("user-1");
    expect(user1Devices).toHaveLength(0);
  });

  it("creates a new row with the new userId after deduplication", async () => {
    const user2Devices = await service.getByUserId("user-2");

    expect(user2Devices).toHaveLength(1);
    expect(user2Devices?.[0].deviceToken).toBe("existing-token");
    expect(user2Devices?.[0].userId).toBe("user-2");
  });
});

describe("UserDeviceService — custom table name", async () => {
  const db = newDb();
  db.public.none(`
    CREATE TABLE custom_devices (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id VARCHAR(255) NOT NULL,
      device_token VARCHAR(255) NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    INSERT INTO custom_devices (user_id, device_token) VALUES ('user-1', 'token-a');
  `);

  const config = createConfig({
    table: { userDevices: { name: "custom_devices" } },
  });
  const database = await createDatabase({ db });
  const service = new UserDeviceService(config, database);

  it("queries the custom table name configured in config.firebase.table.userDevices.name", async () => {
    const result = await service.getByUserId("user-1");

    expect(result).toHaveLength(1);
    expect(result?.[0].deviceToken).toBe("token-a");
  });
});
