const TABLE_FILES = "files";
const BUCKET_FROM_OPTIONS = "optionsBucket";
const BUCKET_FROM_FILE_FIELDS = "fileFieldsBucket";

const OVERWRITE = "overwrite";
const ADD_SUFFIX = "add-suffix";
const ERROR = "error";

const ERROR_CODES = {
  FILE_NOT_FOUND: "FILE_NOT_FOUND_ERROR",
  FILE_ALREADY_EXISTS_IN_S3: "FILE_ALREADY_EXISTS_IN_S3_ERROR",
};

export {
  ADD_SUFFIX,
  BUCKET_FROM_FILE_FIELDS,
  BUCKET_FROM_OPTIONS,
  ERROR,
  ERROR_CODES,
  OVERWRITE,
  TABLE_FILES,
};
