import type { ApiConfig } from "@prefabs.tech/fastify-config";
import type { QuerySqlToken } from "slonik";
import type { ZodTypeAny } from "zod";

import { TABLE_FILES } from "@prefabs.tech/fastify-s3";
import { sql } from "slonik";

import {
  TABLE_INVITATIONS,
  TABLE_USER_PROFILE_FIELD_OPTIONS,
  TABLE_USER_PROFILE_FIELD_OPTIONS_I18N,
  TABLE_USER_PROFILE_FIELDS,
  TABLE_USER_PROFILE_FIELDS_I18N,
  TABLE_USERS,
} from "../constants";

const addProfileInUsersTableQuery = (
  config: ApiConfig,
): QuerySqlToken<ZodTypeAny> => {
  const users = config.user.tables?.users?.name || TABLE_USERS;

  return sql.unsafe`
    ALTER TABLE ${sql.identifier([users])}
    ADD COLUMN IF NOT EXISTS profile JSONB;
  `;
};

const createInvitationsTableQuery = (
  config: ApiConfig,
): QuerySqlToken<ZodTypeAny> => {
  const invitations =
    config.user.tables?.invitations?.name || TABLE_INVITATIONS;

  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([invitations])} (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      accepted_at TIMESTAMP,
      app_id INTEGER,
      email VARCHAR ( 256 ) NOT NULL,
      expires_at TIMESTAMP,
      invited_by_id VARCHAR ( 36 ) NOT NULL,
      payload JSONB,
      revoked_at TIMESTAMP,
      role VARCHAR ( 255 ) NOT NULL,
      token UUID DEFAULT gen_random_uuid() UNIQUE,
      created_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
      FOREIGN KEY ( invited_by_id ) REFERENCES  ${sql.identifier([
        config.user.tables?.users?.name || TABLE_USERS,
      ])} ( id )
    );
  `;
};

const createUsersTableQuery = (
  config: ApiConfig,
): QuerySqlToken<ZodTypeAny> => {
  const users = config.user.tables?.users?.name || TABLE_USERS;

  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([users])} (
      id VARCHAR ( 36 ) PRIMARY KEY,
      disabled BOOLEAN NOT NULL DEFAULT false,
      email VARCHAR ( 256 ) NOT NULL,
      photo_id INTEGER,
      last_login_at TIMESTAMP NOT NULL DEFAULT NOW(),
      signed_up_at TIMESTAMP NOT NULL DEFAULT NOW(),
      deleted_at TIMESTAMP,
      FOREIGN KEY ( photo_id ) REFERENCES ${sql.identifier([
        config.s3?.table?.name || TABLE_FILES,
      ])} ( id )
    );
  `;
};

const createProfileFieldsTablesQueries = (
  config: ApiConfig,
): Array<QuerySqlToken<ZodTypeAny>> => {
  const userProfileFields =
    config.user.tables?.userProfileFields?.name || TABLE_USER_PROFILE_FIELDS;
  const userProfileFieldsI18n =
    config.user.tables?.userProfileFieldsI18n?.name ||
    TABLE_USER_PROFILE_FIELDS_I18N;
  const userProfileFieldOptions =
    config.user.tables?.userProfileFieldOptions?.name ||
    TABLE_USER_PROFILE_FIELD_OPTIONS;
  const userProfileFieldOptionsI18n =
    config.user.tables?.userProfileFieldOptionsI18n?.name ||
    TABLE_USER_PROFILE_FIELD_OPTIONS_I18N;

  const createUserProfileFieldsTableQuery = sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([userProfileFields])} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "default" TEXT DEFAULT NULL,
      disabled BOOLEAN DEFAULT FALSE,
      name VARCHAR(256) NOT NULL,
      required BOOLEAN DEFAULT FALSE NOT NULL,
      sort_order INTEGER DEFAULT 1 NOT NULL,
      type INTEGER NOT NULL,

      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );
  `;

  const createUserProfileFieldsI18nTableQuery = sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([userProfileFieldsI18n])} (
      id INTEGER NOT NULL,
      description TEXT DEFAULT NULL,
      label VARCHAR(256) NOT NULL,
      locale VARCHAR(3) NOT NULL,
      placeholder TEXT DEFAULT NULL,

      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

      FOREIGN KEY (id) REFERENCES ${sql.identifier([userProfileFields])} (id) ON DELETE CASCADE,
      UNIQUE (id, locale)
    );
  `;

  const createUserProfileFieldOptionsTableQuery = sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([userProfileFieldOptions])} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      field_id INTEGER NOT NULL,
      image_id INTEGER DEFAULT NULL,
      rank INTEGER DEFAULT 1 NOT NULL,
      value INTEGER NOT NULL,

      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

      FOREIGN KEY (field_id) REFERENCES ${sql.identifier([userProfileFields])} (id) ON DELETE CASCADE,
      FOREIGN KEY (image_id) REFERENCES ${sql.identifier([config.s3?.table?.name || TABLE_FILES])} (id) ON DELETE SET NULL
    );
  `;

  const createUserProfileFieldOptionsI18nTableQuery = sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([userProfileFieldOptionsI18n])} (
      id INTEGER NOT NULL,
      description TEXT DEFAULT NULL,
      label VARCHAR(256) NOT NULL,
      locale VARCHAR(3) NOT NULL,

      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

      FOREIGN KEY (id) REFERENCES ${sql.identifier([userProfileFieldOptions])} (id) ON DELETE CASCADE,
      UNIQUE (id, locale)
    );
  `;

  return [
    createUserProfileFieldsTableQuery,
    createUserProfileFieldsI18nTableQuery,
    createUserProfileFieldOptionsTableQuery,
    createUserProfileFieldOptionsI18nTableQuery,
  ];
};

const seedProfileFieldsDummyDataQueries = (
  config: ApiConfig,
): Array<QuerySqlToken<ZodTypeAny>> => {
  const userProfileFields =
    config.user.tables?.userProfileFields?.name || TABLE_USER_PROFILE_FIELDS;
  const userProfileFieldOptions =
    config.user.tables?.userProfileFieldOptions?.name ||
    TABLE_USER_PROFILE_FIELD_OPTIONS;
  const userProfileFieldOptionsI18n =
    config.user.tables?.userProfileFieldOptionsI18n?.name ||
    TABLE_USER_PROFILE_FIELD_OPTIONS_I18N;
  const userProfileFieldsI18n =
    config.user.tables?.userProfileFieldsI18n?.name ||
    TABLE_USER_PROFILE_FIELDS_I18N;

  const insertProfileFieldsQuery = sql.unsafe`
    INSERT INTO ${sql.identifier([userProfileFields])} (id, name, type, required, sort_order)
    SELECT seed.id, seed.name, seed.type, seed.required, seed.sort_order
    FROM (
      VALUES
        (1, 'gender', 7, true, 1),
        (2, 'dateOfBirth', 1, true, 2),
        (3, 'location', 3, false, 3)
    ) AS seed(id, name, type, required, sort_order)
    WHERE NOT EXISTS (
      SELECT 1
      FROM ${sql.identifier([userProfileFields])} p
      WHERE p.name = seed.name
    );
  `;

  const upsertProfileFieldsI18nQuery = sql.unsafe`
    INSERT INTO ${sql.identifier([userProfileFieldsI18n])} (id, locale, label)
    SELECT p.id, labels.locale, labels.label
    FROM ${sql.identifier([userProfileFields])} p
    JOIN (
      VALUES
        ('gender', 'en', 'Gender'),
        ('dateOfBirth', 'en', 'Date of birth'),
        ('location', 'en', 'Location')
    ) AS labels(name, locale, label)
      ON labels.name = p.name
    ON CONFLICT (id, locale) DO UPDATE
    SET label = EXCLUDED.label;
  `;

  const insertProfileFieldOptionsQuery = sql.unsafe`
    INSERT INTO ${sql.identifier([userProfileFieldOptions])} (id, field_id, value, rank)
    SELECT seed.id, seed.field_id, seed.value, seed.rank
    FROM (
      VALUES
        (1, 1, 1, 1),
        (2, 1, 2, 2),
        (3, 1, 3, 3)
    ) AS seed(id, field_id, value, rank)
    WHERE NOT EXISTS (
      SELECT 1
      FROM ${sql.identifier([userProfileFieldOptions])} o
      WHERE o.id = seed.id
    );
  `;

  const upsertProfileFieldOptionsI18nQuery = sql.unsafe`
    INSERT INTO ${sql.identifier([userProfileFieldOptionsI18n])} (id, locale, label)
    VALUES
      (1, 'en', 'Male'),
      (2, 'en', 'Female'),
      (3, 'en', 'Other')
    ON CONFLICT (id, locale) DO UPDATE
    SET label = EXCLUDED.label;
  `;

  return [
    insertProfileFieldsQuery,
    upsertProfileFieldsI18nQuery,
    insertProfileFieldOptionsQuery,
    upsertProfileFieldOptionsI18nQuery,
  ];
};

export {
  addProfileInUsersTableQuery,
  createInvitationsTableQuery,
  createProfileFieldsTablesQueries,
  createUsersTableQuery,
  seedProfileFieldsDummyDataQueries,
};
