/* istanbul ignore file */
import { newDb } from "pg-mem";
import { describe, expect, it } from "vitest";

import FeedbackService from "../model/feedback/service";
import createConfig from "./helpers/createConfig";
import createDatabase from "./helpers/createDatabase";

const CREATE_TABLE_SQL = `
  CREATE TABLE feedbacks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id INTEGER NOT NULL,
    message TEXT NOT NULL,
    user_id VARCHAR(255),
    app_version VARCHAR(255),
    device_model VARCHAR(255),
    platform VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
`;

describe("FeedbackService — create", async () => {
  const db = newDb();
  db.public.none(CREATE_TABLE_SQL);

  const config = createConfig();
  const database = await createDatabase({ db });
  const service = new FeedbackService(config, database);

  it("inserts a feedback row and returns it with the provided fields", async () => {
    const result = await service.create({
      appVersion: "1.2.3",
      deviceModel: "Pixel 8",
      message: "Great app",
      platform: "android",
      typeId: 1,
      userId: "user-1",
    });

    expect(result).toMatchObject({
      appVersion: "1.2.3",
      deviceModel: "Pixel 8",
      message: "Great app",
      platform: "android",
      typeId: 1,
      userId: "user-1",
    });
    expect(result.id).toBeDefined();
  });

  it("inserts a row when optional fields are omitted, leaving them null", async () => {
    const result = await service.create({
      message: "Minimal",
      typeId: 2,
    });

    expect(result).toMatchObject({
      message: "Minimal",
      typeId: 2,
    });
    // Optional columns default to null when their keys are omitted from the insert
    expect(result.appVersion).toBeNull();
    expect(result.userId).toBeNull();
  });
});
