import type { ApiConfig } from "@prefabs.tech/fastify-config";
import type { ZodTypeAny } from "zod";

import { QuerySqlToken, sql } from "slonik";

import type { S3Options } from "../types";

import { TABLE_FILES } from "../constants";

// Accepts S3Options (new pattern) or a full ApiConfig (deprecated) during the
// migration window; the ApiConfig overload will be removed in a future release.
const createFilesTableQuery = (
  config: ApiConfig | Partial<S3Options>,
): QuerySqlToken<ZodTypeAny> => {
  const tableName =
    ("s3" in config ? config.s3?.table?.name : config.table?.name) ||
    TABLE_FILES;

  return sql.unsafe`
    CREATE TABLE IF NOT EXISTS ${sql.identifier([tableName])} (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_file_name VARCHAR(255) NOT NULL,
        bucket VARCHAR(255),
        description TEXT,
        key VARCHAR(255) NOT NULL,
        uploaded_by_id VARCHAR(255),
        uploaded_at TIMESTAMP NOT NULL,
        download_count INT DEFAULT 0,
        last_downloaded_at TIMESTAMP,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
`;
};

export { createFilesTableQuery };
