// Invitations
const INVITATION_ACCEPT_LINK_PATH = "/signup/token/:token";
const INVITATION_EXPIRE_AFTER_IN_DAYS = 30;
const ROUTE_INVITATIONS = "/invitations";
const ROUTE_INVITATIONS_ACCEPT = "/invitations/token/:token";
const ROUTE_INVITATIONS_CREATE = "/invitations";
const ROUTE_INVITATIONS_DELETE = String.raw`/invitations/:id(^\d+)`;
const ROUTE_INVITATIONS_GET_BY_TOKEN = "/invitations/token/:token";
const ROUTE_INVITATIONS_RESEND = String.raw`/invitations/resend/:id(^\d+)`;
const ROUTE_INVITATIONS_REVOKE = String.raw`/invitations/revoke/:id(^\d+)`;
const TABLE_INVITATIONS = "invitations";

// Users
const RESET_PASSWORD_PATH = "/reset-password";
const ROLE_ADMIN = "ADMIN";
const ROLE_SUPERADMIN = "SUPERADMIN";
const ROLE_USER = "USER";
const ROUTE_CHANGE_EMAIL = "/change-email";
const ROUTE_CHANGE_PASSWORD = "/change_password";
const ROUTE_SIGNUP_ADMIN = "/signup/admin";
const ROUTE_ME = "/me";
const ROUTE_ME_PHOTO = "/me/photo";
const ROUTE_USERS = "/users";
const ROUTE_USERS_FIND_BY_ID = "/users/:id";
const ROUTE_USERS_DISABLE = "/users/:id/disable";
const ROUTE_USERS_ENABLE = "/users/:id/enable";
const TABLE_USERS = "users";

// User profile fields
const ROUTE_USER_PROFILE = "/users/profile";
const ROUTE_USER_PROFILE_FIELDS = "/profile/fields";
const TABLE_USER_PROFILE_FIELD_OPTIONS = "user_profile_field_options";
const TABLE_USER_PROFILE_FIELD_OPTIONS_I18N = "user_profile_field_options_i18n";
const TABLE_USER_PROFILE_FIELDS = "user_profile_fields";
const TABLE_USER_PROFILE_FIELDS_I18N = "user_profile_fields_i18n";
const USER_PROFILE_FIELD_TYPES = {
  DATE: 1,
  EMAIL: 2,
  LOCATION: 3,
  MIN_MAX_INPUT: 12,
  MULTI_IMAGE_UPLOAD: 9,
  MULTI_SELECT: 4,
  MULTI_SELECT_BADGE: 5,
  NAME: 6,
  SINGLE_SELECT: 7,
  TEXT: 8,
  TEXT_AREA: 10,
  URL: 11,
};

// Roles
const ROUTE_ROLES = "/roles";
const ROUTE_ROLES_PERMISSIONS = "/roles/permissions";

// Permissions
const ROUTE_PERMISSIONS = "/permissions";

// Email verification
const EMAIL_VERIFICATION_MODE = "REQUIRED";
const EMAIL_VERIFICATION_PATH = "/verify-email";

const PERMISSIONS_INVITATIONS_CREATE = "invitations:create";
const PERMISSIONS_INVITATIONS_DELETE = "invitations:delete";
const PERMISSIONS_INVITATIONS_LIST = "invitations:list";
const PERMISSIONS_INVITATIONS_RESEND = "invitations:resend";
const PERMISSIONS_INVITATIONS_REVOKE = "invitations:revoke";

const PERMISSIONS_USERS_DISABLE = "users:disable";
const PERMISSIONS_USERS_ENABLE = "users:enable";
const PERMISSIONS_USERS_LIST = "users:list";
const PERMISSIONS_USERS_READ = "users:read";

// Default max size for user photo in MB
const DEFAULT_USER_PHOTO_MAX_SIZE_IN_MB = 5;

const ERROR_CODES = {
  CHANGE_PASSWORD: "CHANGE_PASSWORD_ERROR",
  INVALID_EMAIL: "INVALID_EMAIL_ERROR",
  INVALID_PASSWORD: "INVALID_PASSWORD_ERROR",
  INVITATION_ALREADY_EXISTS: "INVITATION_ALREADY_EXISTS_ERROR",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND_ERROR",
  PHOTO_FILE_MISSING: "PHOTO_FILE_MISSING_ERROR",
  PHOTO_FILE_TOO_LARGE: "PHOTO_FILE_TOO_LARGE_ERROR",
  ROLE_ALREADY_EXISTS: "ROLE_ALREADY_EXISTS_ERROR",
  ROLE_IN_USE: "ROLE_IN_USE_ERROR",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND_ERROR",
  ROLE_NOT_SUPPORTED: "ROLE_NOT_SUPPORTED_ERROR",
  UNKNOWN_ROLE_ERROR: "UNKNOWN_ROLE_ERROR",
  UNSUPPORTED_PHOTO_FILE_TYPE: "UNSUPPORTED_PHOTO_FILE_TYPE_ERROR",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND_ERROR",
};

const SUPERTOKENS_CORS_HEADERS = [
  "anti-csrf",
  "authorization",
  "fdi-version",
  "front-token",
  "rid",
  "st-access-token",
  "st-auth-mode",
  "st-refresh-token",
];

export {
  DEFAULT_USER_PHOTO_MAX_SIZE_IN_MB,
  EMAIL_VERIFICATION_MODE,
  EMAIL_VERIFICATION_PATH,
  ERROR_CODES,
  INVITATION_ACCEPT_LINK_PATH,
  INVITATION_EXPIRE_AFTER_IN_DAYS,
  PERMISSIONS_INVITATIONS_CREATE,
  PERMISSIONS_INVITATIONS_DELETE,
  PERMISSIONS_INVITATIONS_LIST,
  PERMISSIONS_INVITATIONS_RESEND,
  PERMISSIONS_INVITATIONS_REVOKE,
  PERMISSIONS_USERS_DISABLE,
  PERMISSIONS_USERS_ENABLE,
  PERMISSIONS_USERS_LIST,
  PERMISSIONS_USERS_READ,
  RESET_PASSWORD_PATH,
  ROLE_ADMIN,
  ROLE_SUPERADMIN,
  ROLE_USER,
  ROUTE_CHANGE_EMAIL,
  ROUTE_CHANGE_PASSWORD,
  ROUTE_INVITATIONS,
  ROUTE_INVITATIONS_ACCEPT,
  ROUTE_INVITATIONS_CREATE,
  ROUTE_INVITATIONS_DELETE,
  ROUTE_INVITATIONS_GET_BY_TOKEN,
  ROUTE_INVITATIONS_RESEND,
  ROUTE_INVITATIONS_REVOKE,
  ROUTE_ME,
  ROUTE_ME_PHOTO,
  ROUTE_PERMISSIONS,
  ROUTE_ROLES,
  ROUTE_ROLES_PERMISSIONS,
  ROUTE_SIGNUP_ADMIN,
  ROUTE_USER_PROFILE,
  ROUTE_USER_PROFILE_FIELDS,
  ROUTE_USERS,
  ROUTE_USERS_DISABLE,
  ROUTE_USERS_ENABLE,
  ROUTE_USERS_FIND_BY_ID,
  SUPERTOKENS_CORS_HEADERS,
  TABLE_INVITATIONS,
  TABLE_USER_PROFILE_FIELD_OPTIONS,
  TABLE_USER_PROFILE_FIELD_OPTIONS_I18N,
  TABLE_USER_PROFILE_FIELDS,
  TABLE_USER_PROFILE_FIELDS_I18N,
  TABLE_USERS,
  USER_PROFILE_FIELD_TYPES,
};
