/* istanbul ignore file */
import { newDb } from "pg-mem";
import { describe, expect, it } from "vitest";

import type { SlonikOptions } from "../types";

import createConfig from "./helpers/createConfig";
import createDatabase from "./helpers/createDatabase";
import TestSqlFactory from "./helpers/sqlFactory";
import TestService from "./helpers/testService";
import {
  getFilterDataset,
  getLimitAndOffsetDataset,
  getSortDataset,
} from "./helpers/utils";

describe("Service", async () => {
  const db = newDb();

  db.public.none(`
    create table test(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, latitude INT, country_code TEXT);
    insert into test (name, latitude, country_code) values ('Test1', 20, 'NP'), ('Test2', 30, 'US');
    create schema tenant1;
    create table tenant1.test(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, latitude INT, country_code TEXT);
    insert into tenant1.test (name, latitude, country_code) values ('Test1', 20, 'NP'), ('Test2', 30, 'US');
  `);

  const config = createConfig();
  const database = await createDatabase({ db });

  it("returns table name", async () => {
    const service = new TestService(config, database);

    expect(service.table).toBe(TestSqlFactory.TABLE);
  });

  it("returns class default limit", async () => {
    const service = new TestService(config, database);

    expect(service.factory.limitDefault).toBe(TestSqlFactory.LIMIT_DEFAULT);
  });

  it("returns class max limit", async () => {
    const service = new TestService(config, database, "test");

    expect(service.factory.limitMax).toBe(TestSqlFactory.LIMIT_MAX);
  });

  it("returns default limit as per config", async () => {
    const config = {
      db: {
        databaseName: "test",
        host: "localhost",
        password: "password",
        username: "username",
      },
      pagination: {
        defaultLimit: 5,
        maxLimit: 10,
      },
    } as SlonikOptions;

    const service = new TestService(createConfig(config), database, "test");

    expect(service.factory.limitDefault).toBe(config.pagination?.defaultLimit);
  });

  it("returns max limit as per config", async () => {
    const config = {
      db: {
        databaseName: "test",
        host: "localhost",
        password: "password",
        username: "username",
      },
      pagination: {
        defaultLimit: 5,
        maxLimit: 10,
      },
    } as SlonikOptions;

    const service = new TestService(createConfig(config), database);

    expect(service.factory.limitMax).toBe(config.pagination?.maxLimit);
  });

  it("returns count", async () => {
    const result = [{ count: 2 }];

    const service = new TestService(config, database);

    const response = await service.count();

    expect(response).toBe(result[0].count);
  });

  it("calls database with correct sql query for all method", async () => {
    const result = [
      { id: 1, name: "Test1" },
      { id: 2, name: "Test2" },
    ];

    const service = new TestService(config, database);

    const data = ["id", "name"];

    const response = await service.all(data);

    expect(response).toStrictEqual(result);
  });

  it("calls database with correct sql query for find method", async () => {
    const result = [
      { countryCode: "NP", id: 1, latitude: 20, name: "Test1" },
      { countryCode: "US", id: 2, latitude: 30, name: "Test2" },
    ];

    const service = new TestService(config, database);

    const response = await service.find();

    expect(response).toStrictEqual(result);
  });

  it("calls database with correct sql query for findOne method", async () => {
    const result = { countryCode: "NP", id: 1, latitude: 20, name: "Test1" };

    const service = new TestService(config, database);

    const response = await service.findOne(
      { key: "id", operator: "eq", value: "1" },
      [{ direction: "ASC", key: "id" }],
    );

    expect(response).toStrictEqual(result);
  });

  it("calls database with correct sql query for create method", async () => {
    const result = [{ countryCode: "FR", id: 3, latitude: 20, name: "Test" }];

    const service = new TestService(config, database);

    const data = { countryCode: "FR", latitude: 20, name: "Test" };

    const response = await service.create(data);

    expect(response).toStrictEqual(result[0]);
  });

  it("calls database with correct sql query for findById method", async () => {
    const data = 1;

    const result = [{ countryCode: "NP", id: 1, latitude: 20, name: "Test1" }];

    const service = new TestService(config, database);

    const response = await service.findById(data);

    expect(response).toStrictEqual(result[0]);
  });

  it("calls database with correct sql query for update method", async () => {
    const data = { name: "updated test" };

    const result = [{ id: 1, ...data, countryCode: "NP", latitude: 20 }];

    const service = new TestService(config, database);

    const response = await service.update(1, data);

    expect(response).toStrictEqual(result[0]);
  });

  it("calls database with correct sql query for delete method", async () => {
    const id = 3;

    const result = [{ countryCode: "FR", id: 3, latitude: 20, name: "Test" }];

    const service = new TestService(config, database);

    const response = await service.delete(id);

    expect(response).toStrictEqual(result[0]);
  });

  it("calls database with correct sql query for create method for other schema", async () => {
    const result = [
      { id: 1, name: "Test1" },
      { id: 2, name: "Test2" },
    ];

    const service = new TestService(config, database, "tenant1");

    const data = ["id", "name"];

    const response = await service.all(data);

    expect(response).toStrictEqual(result);
  });

  it("calls database with correct sql queries for list method", async () => {
    const service = new TestService(config, database);

    const response = await service.list();

    expect(response).toHaveProperty("totalCount");
    expect(response).toHaveProperty("filteredCount");
    expect(response).toHaveProperty("data");
    expect(response).toHaveProperty("filteredCount");
  });

  it("calls database with correct sql query for list method with limit and offset arguments", async () => {
    const count = 190;

    const dataset = await getLimitAndOffsetDataset(count, config);

    const service = new TestService(config, database);

    for await (const set of dataset) {
      const { limit, offset } = set();

      const response = await service.list(limit, offset);

      expect(response).toHaveProperty("totalCount");
      expect(response).toHaveProperty("filteredCount");
      expect(response).toHaveProperty("data");
    }
  });

  it("calls database with correct sql queries for list method with filter", async () => {
    const service = new TestService(config, database);

    const limit = 190;

    const filterInputs = getFilterDataset();

    for (const filterInput of filterInputs) {
      const response = await service.list(limit, undefined, filterInput);

      expect(response).toHaveProperty("totalCount");
      expect(response).toHaveProperty("filteredCount");
      expect(response).toHaveProperty("data");
    }
  });

  it("calls database with correct sql queries for list method with sort", async () => {
    const service = new TestService(config, database);

    const limit = 190;

    const sortInputs = getSortDataset();

    for (const sortInput of sortInputs) {
      const response = await service.list(
        limit,
        undefined,
        undefined,
        sortInput,
      );

      expect(response).toHaveProperty("totalCount");
      expect(response).toHaveProperty("filteredCount");
      expect(response).toHaveProperty("data");
    }
  });
});

describe("BaseService — isCompatibleType edge cases", async () => {
  const db = newDb();
  db.public.none(
    `create table test(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, latitude INT, country_code TEXT);
     insert into test (name, latitude, country_code) values ('Edge1', 10, 'DE');`,
  );
  const config = createConfig();
  const database = await createDatabase({ db });

  class InspectService extends TestService<
    Record<string, unknown>,
    Record<string, unknown>,
    Record<string, unknown>
  > {
    // Expose protected method for testing
    testIsCompatibleType<T>(processed: T, original: T): boolean {
      return this.isCompatibleType(processed, original);
    }
  }

  it("returns true when original is undefined (processed can be anything)", () => {
    const service = new InspectService(config, database);
    expect(service.testIsCompatibleType("anything")).toBe(true);
  });

  it("returns false when processed is array but original is plain object", () => {
    const service = new InspectService(config, database);
    expect(service.testIsCompatibleType([], {})).toBe(false);
  });

  it("returns false when processed is object but original is array", () => {
    const service = new InspectService(config, database);
    expect(service.testIsCompatibleType({}, [])).toBe(false);
  });

  it("returns false when null processed does not match non-null original", () => {
    const service = new InspectService(config, database);
    // eslint-disable-next-line unicorn/no-null
    expect(service.testIsCompatibleType(null, {})).toBe(false);
  });
});
