import type { ApiConfig } from "@prefabs.tech/fastify-config";

import { newDb } from "pg-mem";
import { describe, expect, it } from "vitest";

import type { Database } from "../types";

import DefaultSqlFactory from "../sqlFactory";
import createConfig from "./helpers/createConfig";
import createDatabase from "./helpers/createDatabase";

class HardDeleteFactory extends DefaultSqlFactory {
  static readonly TABLE = "test";
}

class SoftDeleteFactory extends DefaultSqlFactory {
  static readonly TABLE = "test";
  protected _softDeleteEnabled = true;
}

const makeFactory = async (
  FactoryClass: typeof DefaultSqlFactory,
  config: ApiConfig,
  database: Database,
) => new FactoryClass(config, database);

describe("DefaultSqlFactory — soft delete", async () => {
  const db = newDb();
  db.public.none(
    `create table test(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, deleted_at TIMESTAMP);`,
  );
  const config = createConfig();
  const database = await createDatabase({ db });

  it("getDeleteSql generates UPDATE SET deleted_at when soft-delete is enabled", async () => {
    const factory = await makeFactory(SoftDeleteFactory, config, database);
    const query = factory.getDeleteSql(1);
    expect(query.sql).toMatch(/UPDATE/i);
    expect(query.sql).toMatch(/deleted_at/i);
    expect(query.sql).not.toMatch(/DELETE FROM/i);
  });

  it("getDeleteSql with force=true generates DELETE even when soft-delete is enabled", async () => {
    const factory = await makeFactory(SoftDeleteFactory, config, database);
    const query = factory.getDeleteSql(1, true);
    expect(query.sql).toMatch(/DELETE FROM/i);
  });

  it("getDeleteSql generates DELETE when soft-delete is disabled", async () => {
    const factory = await makeFactory(HardDeleteFactory, config, database);
    const query = factory.getDeleteSql(1);
    expect(query.sql).toMatch(/DELETE FROM/i);
  });

  it("getSoftDeleteFilterFragment returns empty fragment when soft-delete disabled", async () => {
    const factory = await makeFactory(HardDeleteFactory, config, database);
    const fragment = factory["getSoftDeleteFilterFragment"](true);
    expect(fragment.sql.trim()).toBe("");
  });

  it("getSoftDeleteFilterFragment returns WHERE clause when addWhere is true", async () => {
    const factory = await makeFactory(SoftDeleteFactory, config, database);
    const fragment = factory["getSoftDeleteFilterFragment"](true);
    expect(fragment.sql).toMatch(/WHERE/i);
    expect(fragment.sql).toMatch(/deleted_at IS NULL/);
  });

  it("getSoftDeleteFilterFragment returns AND clause when addWhere is false", async () => {
    const factory = await makeFactory(SoftDeleteFactory, config, database);
    const fragment = factory["getSoftDeleteFilterFragment"](false);
    expect(fragment.sql).toMatch(/AND/i);
    expect(fragment.sql).toMatch(/deleted_at IS NULL/);
  });
});

describe("DefaultSqlFactory — static defaults", () => {
  it("LIMIT_DEFAULT is 20", () => {
    expect(DefaultSqlFactory.LIMIT_DEFAULT).toBe(20);
  });

  it("LIMIT_MAX is 50", () => {
    expect(DefaultSqlFactory.LIMIT_MAX).toBe(50);
  });

  it("SORT_DIRECTION is ASC", () => {
    expect(DefaultSqlFactory.SORT_DIRECTION).toBe("ASC");
  });

  it("SORT_KEY is id", () => {
    expect(DefaultSqlFactory.SORT_KEY).toBe("id");
  });
});

describe("DefaultSqlFactory — default schema", async () => {
  const db = newDb();
  db.public.none(
    `create table test(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT);`,
  );
  const config = createConfig();
  const database = await createDatabase({ db });

  class SimpleFactory extends DefaultSqlFactory {
    static readonly TABLE = "test";
  }

  it("schema is public when no schema passed to constructor", async () => {
    const factory = await makeFactory(SimpleFactory, config, database);
    expect(factory.schema).toBe("public");
  });

  it("schema uses provided value when passed", async () => {
    const factory = new SimpleFactory(config, database, "tenant1");
    expect(factory.schema).toBe("tenant1");
  });
});

describe("DefaultSqlFactory — deprecated getTableFragment", async () => {
  const db = newDb();
  db.public.none(
    `create table test(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT);`,
  );
  const config = createConfig();
  const database = await createDatabase({ db });

  class SimpleFactory extends DefaultSqlFactory {
    static readonly TABLE = "test";
  }

  it("getTableFragment (deprecated) returns the same result as tableFragment getter", async () => {
    const factory = await makeFactory(SimpleFactory, config, database);
    expect(factory.getTableFragment().sql).toBe(factory.tableFragment.sql);
  });
});
