import type { ApiConfig } from "@prefabs.tech/fastify-config";
import type { QuerySqlToken } from "slonik";
import type { ZodTypeAny } from "zod";

import { sql } from "slonik";

import { TABLE_FEEDBACKS } from "../constants";

const createFeedbacksTableQuery = (
  config: ApiConfig,
): QuerySqlToken<ZodTypeAny> => {
  const tableName = config.feedback.table?.feedbacks?.name || TABLE_FEEDBACKS;

  return sql.unsafe`
    DO $$
    BEGIN
      CREATE TABLE IF NOT EXISTS ${sql.identifier([tableName])} (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        app_version VARCHAR(255),
        device_model VARCHAR(255),
        message TEXT NOT NULL,
        platform VARCHAR(255),
        type_id INTEGER NOT NULL,
        user_id VARCHAR(255),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );

      CREATE INDEX IF NOT EXISTS idx_feedbacks_user_id ON ${sql.identifier([
        tableName,
      ])} (user_id);
    END $$;
  `;
};

export { createFeedbacksTableQuery };
